baseURL:
languageCode: en-us
title: Aekjeldal
theme: hugo-PaperMod



params:
  math: true
  name: Anders Egelund Kjeldal
  github: https://github.com/AEKjeldal/
  rss:  true                                # show rss icon
  ShowReadingTime: true
  ShowBreadcrumbs: true
  ShowPostNavLinks: true
  homeInfoParams:
      Title: "Aekjeldal"
      Content: ""

markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        # noClasses: false
        style: monokai
